app = "vixter-centrifugo"
primary_region = "atl"

[build]
  dockerfile = "Dockerfile"

[[services]]
protocol = "tcp"
internal_port = 8000

[[services.ports]]
port = 80
handlers = ["http"]

[[services.ports]]
port = 443
handlers = ["tls", "http"]
